apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: springboot-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081   # Spring Boot runs on 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/springboot_jdbc?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"

            - name: SPRING_DATASOURCE_USERNAME
              value: "root"

            - name: SPRING_DATASOURCE_PASSWORD
              value: "root@123"
