name: build-deploy

on:
  push:
    branches:
      - Develop

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build Maven Package
        run: mvn -DskipTests clean package

      - name: Use Minikube Docker Daemon
        run: minikube -p minikube docker-env | Out-String | Invoke-Expression

      - name: Build Docker Image inside Minikube
        run: docker build -t springboot-app:latest .

      - name: Load Image into Minikube
        run: minikube image load springboot-app:latest

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/

      - name: Rollout Status
        run: kubectl rollout status deployment/springboot-app
